#Default
calc_features_sky : True
cal_features_qts : True
col_dict : {ML QTs : xgb_dense_QTS_0 , ML combined: densnet_xgbsky_bayestar_mul_0, ML sky : xgb_pred_bayestar_skymaps}
calc_fpp : True
#Data
in_df : /home/srashti.goyal/lensid-ml-O3/O3_ML/dataframes/filtered_sky_mass_pairs.csv
data_dir_qts : /home/srashti.goyal/lensid-ml-O3/O3_ML/qts/
whitened : False
include_phenom : False
data_dir_sky : /home/srashti.goyal/lensid-ml-O3/O3_ML/bayestar_skymaps/
odir : O3_events
tag_qts : _kaggle
tag_sky : ''
#ML Models
dense_model_dir: /home/srashti.goyal/lensid/saved_models/
xgboost_qt : /home/srashti.goyal/lensid/saved_models/XGBQT_0.pkl
xgboost_sky : /home/srashti.goyal/lensid/saved_models/XGBsky_0.pkl
#Background
fpp_dict : {ML QTs : xgb_dense_QTS , ML combined: densnet_xgbsky_bayestar_mul, ML sky : xgb_pred_bayestar_skymaps}
background_df : /home/srashti.goyal/lensid-ml-O3/O3_ML/dataframes/O3a_injs_ML_combined_git.csv