#[DEFAULT]
base_out_dir : /home/srashti.goyal/lensid_runs
train_densenets : 1
calc_features_sky : 0
cal_features_qts : 1
train_test_qts : 1
train_test_sky : 1
test_combined_ml : 1
compare_to_blu : 1
df_dir_train : /home/srashti.goyal/strong-lensing-ml/data/dataframes/train/
df_dir_test : /home/srashti.goyal/strong-lensing-ml/data/dataframes/test/
whitened : 0

#[train-densenets]
epochs : 10
lensed_df : lensed.csv
unlensed_df : unlensed_half.csv
train_h1 : 1
train_l1 : 1
train_v1 : 1
h1_lr : 0.01
l1_lr : 0.01 
v1_lr : 0.01 
size_lensed : 1400
size_unlensed : 1400
include_phenom : 1
dense_model_dir_out : /saved_models/ #relative to base_out_dir

#[feature-extraction]
dense_model_dir_in : /home/srashti.goyal/lensid/saved_models/
df_dir_train_features_out : /dataframes/train/ #relative to base_out_dir
df_dir_test_features_out : /dataframes/test/ #relative to base_out_dir
data_dir_qts_train : /home/srashti.goyal/alice_data_lensid/qts/train/
data_dir_qts_test : /home/srashti.goyal/alice_data_lensid/qts/test/
data_dir_sky_train : /home/srashti.goyal/alice_data_lensid/bayestar_skymaps/train
data_dir_sky_test : /home/srashti.goyal/alice_data_lensid/bayestar_skymaps/test
tag_qts_out : '' #_kaggle
tag_sky_out : ''
train_dfs_dict : { lensed : 100 , unlensed_half : 100 , unlensed_second_half : 100}
#train_dfs_dict : { lensed : -1 , unlensed_half : -1 , unlensed_second_half : -1}
test_dfs_dict : {lensed : 100 , unlensed : 100}
#test_dfs_dict : {lensed : -1 , unlensed : -1}
    
#[train-test-cv-qts]
df_dir_train_features_in : /home/srashti.goyal/strong-lensing-ml/data/dataframes/train/
df_dir_test_features_in : /home/srashti.goyal/strong-lensing-ml/data/dataframes/test/
path_to_blu : /home/srashti.goyal/strong-lensing-ml/data/dataframes/haris_et_al/
train_size_lensed_xgbqts : 2400
cv_size_lensed_xgbqts : 2400
cv_splits_xgbqts : 10
scale_pos_weight_xgbqts : 0.01
max_depth_xgbqts : 6
n_estimators_xgbqts : 135
tag_qts_in : _kaggle

#[train-test-cv-sky]
train_size_lensed_xgbsky : 2400
cv_size_lensed_xgbsky : 2400
cv_splits_xgbsky : 10
scale_pos_weight_xgbsky : 0.01
max_depth_xgbsky : 6
n_estimators_xgbsky : 110
tag_sky_in : ''

#[test-ml-combined]
indir_df : /home/srashti.goyal/strong-lensing-ml/data/dataframes/test 

#python train_densenets_QTs.py -lensed_df ~/strong-lensing-ml/data/dataframes/train/lensed.csv -unlensed_df ~/strong-lensing-ml/data/dataframes/train/unlensed_half.csv -odir dense_out/cit/ -epochs 10 -data_dir ~/alice_data_lensid/qts/train/